name: Status for ESP32

on:
  workflow_dispatch:
    inputs:
      status:
        required: true
        type: string

jobs:
  update-status-badge:
    runs-on: ubuntu-latest
    steps:
      - run: test "${{ inputs.status }}" = "success"
