name: Integration Tests
on: [push, pull_request]

jobs:
  ArduinoAVR:
    uses: ./.github/workflows/Test-ArduinoAVR.yml

  ArduinoSAMD:
    uses: ./.github/workflows/Test-ArduinoSAMD.yml

  ATTinyCore:
    uses: ./.github/workflows/Test-ATTinyCore.yml

  ESP32:
    uses: ./.github/workflows/Test-ESP32.yml

  ESP8266:
    uses: ./.github/workflows/Test-ESP8266.yml

  STM32:
    uses: ./.github/workflows/Test-STM32.yml

