name: Integration Tests

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string

      board:
        required: true
        type: string

jobs:
  testing:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install platform
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli config add board_manager.additional_urls https://drazzy.com/package_drazzy.com_index.json
          arduino-cli config add board_manager.additional_urls https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json
          arduino-cli config dump

          arduino-cli core update-index
          arduino-cli core install ${{ inputs.platform }}

      - name: Install Ninja
        id: ninja
        run: |
            $releaseUrl = "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-win.zip"
            $expectedHash = "F550FEC705B6D6FF58F2DB3C374C2277A37691678D6ABA463ADCBB129108467A"

            Invoke-WebRequest -Uri $releaseUrl -OutFile ninja.zip
            Expand-Archive -Path ninja.zip -DestinationPath ninja

            $actualHash = (Get-FileHash -Path ninja.zip -Algorithm SHA256).Hash
            if ($actualHash -ne $expectedHash) { exit 1 }

            echo "PATH=$PWD/ninja;$env:PATH" >> $env:GITHUB_ENV

      - name: Configure test suite
        run: |
          mkdir test
          cd test

          $boardIds = "${{ format('{0}:{1}', inputs.platform, inputs.board) }}"
          cmake ..  -G Ninja -D "ARDUINO_CLI_TOOLCHAIN_TESTED_BOARDS=$boardIds"

      - name: Run the test suite
        run: |
          cd test
          ctest --build-config Debug -V
