name: STM32 Nucleo 64

on:
  workflow_call:
    inputs:
      dummy:
        required: false
        type: boolean

jobs:
  call-workflow:
    uses: ./.github/workflows/RunTestSuite.yml
    with:
      platform: STMicroelectronics:stm32
