name: ATTiny Core

on:
  workflow_call:
    inputs:
      dummy:
        required: false
        type: boolean

jobs:
  call-workflow:
    uses: ./.github/workflows/RunTestSuite.yml
    with:
      platform: ATTinyCore:avr
